/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { SchoolStat, Program, NewsItem, Achievement, AgendaEvent, GalleryPhoto, FAQItem, DownloadFile } from "./types";

export const schoolStats: SchoolStat[] = [
  {
    id: "students",
    count: 312,
    suffix: "+",
    label: "Siswa Aktif",
    icon: "Users",
  },
  {
    id: "teachers",
    count: 18,
    suffix: "",
    label: "Guru & Staff",
    icon: "GraduationCap",
  },
  {
    id: "classrooms",
    count: 12,
    suffix: "",
    label: "Ruang Belajar & Lab",
    icon: "School",
  },
  {
    id: "achievements",
    count: 35,
    suffix: "+",
    label: "Piala & Penghargaan",
    icon: "Trophy",
  },
];

export const schoolPrograms: Program[] = [
  {
    id: "prog-tahfiz",
    title: "Tahfidz Al-Qur'an Juz 30",
    description: "Pendampingan khusus hafalan Juz Amma untuk membina karakter agamis, disiplin, dan akhlak mulia sejak dini.",
    category: "unggulan",
    icon: "BookOpen",
    color: "from-blue-500 to-blue-700",
  },
  {
    id: "prog-literasi",
    title: "Literasi & Numerasi Digital",
    description: "Pembiasaan membaca buku, bercerita, serta game logika matematika interaktif 15 menit setiap pagi sebelum pelajaran.",
    category: "unggulan",
    icon: "Cpu",
    color: "from-amber-500 to-amber-600",
  },
  {
    id: "prog-ramah",
    title: "Sekolah Ramah Anak",
    description: "Komitmen penuh menjaga lingkungan belajar nihil perundungan, penuh toleransi, bersih, aman, sehat, dan menyenangkan.",
    category: "unggulan",
    icon: "Heart",
    color: "from-emerald-500 to-emerald-600",
  },
  {
    id: "prog-adiwiyata",
    title: "Adiwiyata Lestari",
    description: "Edukasi praktis peduli ekologi melalui pemilahan sampah organik-anorganik, kebun hidroponik, dan penghematan energi.",
    category: "unggulan",
    icon: "Leaf",
    color: "from-teal-500 to-green-600",
  },
  {
    id: "ekskul-pramuka",
    title: "Pramuka Siaga & Penggalang",
    description: "Melatih kepanduan dasar, kemandirian, kekompakan kelompok, darurat P3K, dan karakter gotong royong anak.",
    category: "ekskul",
    icon: "Compass",
    color: "from-amber-700 to-amber-900",
  },
  {
    id: "ekskul-rebana",
    title: "Ekstra Rebana & Seni Musik",
    description: "Wadah mengasah bakat seni ketukan Islami tradisional dan pelatihan paduan suara lagu kebangsaan & daerah.",
    category: "ekskul",
    icon: "Music",
    color: "from-purple-500 to-indigo-600",
  },
  {
    id: "ekskul-silat",
    title: "Pencak Silat Seni",
    description: "Pelatihan seni bela diri khas Nusantara untuk mengasah kebugaran fisik, refleks pertahanan diri, dan sportivitas.",
    category: "ekskul",
    icon: "ShieldAlert",
    color: "from-red-500 to-rose-600",
  },
  {
    id: "ekskul-melukis",
    title: "Seni Lukis & Kaligrafi",
    description: "Medium berekspresi secara visual, mengeksplorasi warna, melukis pemandangan, poster, dan keindahan seni khot.",
    category: "ekskul",
    icon: "Palette",
    color: "from-pink-500 to-red-500",
  },
  {
    id: "ekskul-dokter",
    title: "Dokter Kecil & UKS",
    description: "Bimbingan gaya hidup bersih, pemeriksaan kesehatan kuku/gigi berkala, dan penanganan cedera ringan.",
    category: "ekskul",
    icon: "HeartPulse",
    color: "from-red-600 to-red-700",
  },
  {
    id: "ekskul-olahraga",
    title: "Futsal & Atletik",
    description: "Latihan fisik terjadwal untuk meningkatkan stamina, teknik dasar dribbling, passing, dan turnamen antarkelas.",
    category: "ekskul",
    icon: "Activity",
    color: "from-cyan-500 to-blue-600",
  },
  {
    id: "intra-pancasila",
    title: "Pendidikan Karakter & Pancasila",
    description: "Pembelajaran inti yang mengintegrasikan nilai-nilai luhur Pancasila dalam setiap mata pelajaran secara terstruktur dan aplikatif.",
    category: "intrakurikuler",
    icon: "GraduationCap",
    color: "from-blue-600 to-indigo-700",
  },
  {
    id: "intra-sains",
    title: "Sains & Matematika Eksperimental",
    description: "Pendalaman kompetensi saintifik melalui eksperimen laboratorium sederhana dan eksplorasi logika matematika yang kreatif dan menyenangkan.",
    category: "intrakurikuler",
    icon: "Cpu",
    color: "from-teal-600 to-indigo-700",
  },
  {
    id: "kokur-p5",
    title: "Projek Penguatan Profil Pelajar Pancasila (P5)",
    description: "Projek pembelajaran berbasis kelompok lintas disiplin ilmu untuk merumuskan aksi dan solusi nyata atas topik kearifan lokal serta isu lingkungan hidup.",
    category: "kokurikuler",
    icon: "Heart",
    color: "from-emerald-600 to-green-700",
  },
  {
    id: "kokur-market",
    title: "Market Day & Wirausaha Mandiri",
    description: "Sesi praktik kewirausahaan berkala untuk memupuk jiwa mandiri, kreativitas, empati, inovasi pangan sehat, serta pengenalan literasi finansial sejak dini.",
    category: "kokurikuler",
    icon: "Store",
    color: "from-pink-600 to-rose-700",
  },
];

export const latestNews: NewsItem[] = [
  {
    id: "news-1",
    title: "SDN 3 Purwosari Sukses Raih Akreditasi 'A' Unggul Tahun 2026",
    excerpt: "Berkat kerja keras para guru, komite, dan dukungan wali murid, badan akreditasi nasional resmi menetapkan nilai unggul.",
    content: "Wonogiri — SDN 3 Purwosari berhasil memperbarui status akreditasi sekolah dengan capaian predikat 'A' Unggul dari Badan Akreditasi Nasional (BAN) pada penilaian awal tahun 2026. Penilaian komprehensif ini mencakup kelayakan mutu lulusan, proses pembelajaran yang interaktif dan ramah anak, kompetensi pendidik, serta prasarana sekolah yang mumpuni. Kepala Sekolah merasa bersyukur dan berjanji akan terus mempertahankan dedikasi mendidik putra-putri Wonogiri dengan sepenuh hati.",
    date: "10 Jun 2026",
    category: "Akademik",
    image: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&q=80&w=600",
    author: "Tim Humas Sekolah",
  },
  {
    id: "news-2",
    title: "Pelepasan Siswa Kelas VI Tahun Ajaran 2025/2026 Berlangsung Haru",
    excerpt: "Acara kelulusan dimeriahkan oleh pentas seni tari tradisional Jawa dan pembacaan puisi dari perwakilan wali siswa.",
    content: "Wonogiri — Sebanyak 42 siswa kelas VI SDN 3 Purwosari Wonogiri secara resmi dikembalikan kepada orang tua dalam upacara pelepasan kelulusan yang dilangsungkan di aula warga setempat. Acara tersebut diwarnai dengan penyerahan sertifikat kelulusan, suguhan tari kreasi tradisional persembahan adik-adik kelas, serta pidato penuh haru dari perwakilan murid yang mengucapkan terima kasih atas bimbingan guru selama enam tahun penuh kenangan.",
    date: "05 Jun 2026",
    category: "Kegiatan",
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=600",
    author: "Panitia Wisuda",
  },
  {
    id: "news-3",
    title: "Pemberian Imunisasi BIAS Puskesmas Wonogiri II Berjalan Lancar",
    excerpt: "Pemberian imunisasi difteri dan tetanus bagi seluruh siswa kelas 1, 2, dan 5 guna memperkuat kekebalan tubuh anak.",
    content: "Purwosari — Tim medis dari Puskesmas Wonogiri II melakukan kunjungan berkala ke SDN 3 Purwosari dalam agenda Bulan Imunisasi Anak Sekolah (BIAS). Didampingi oleh bapak ibu guru wali kelas, proses screening dan penyuntikan vaksin imunisasi berjalan dengan sangat lancar dan tertib. Langkah preventif ini penting untuk memproteksi anak-anak dari ancaman penyakit difteri dan tetanus.",
    date: "28 Mei 2026",
    category: "Kesehatan",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=600",
    author: "Dokter Kecil",
  },
  {
    id: "news-4",
    title: "Pendaftaran Siswa Baru (PPDB / SPMB) TA 2026/2027 Resmi Dibuka Online",
    excerpt: "Simak petunjuk berkas, rentang usia, kuota zonasi, dan alur pendaftaran mandiri lewat portal resmi sekolah di sini.",
    content: "Wonogiri — Menyambut tahun pelajaran baru, SDN 3 Purwosari Wonogiri membuka pendaftaran peserta didik baru. Pada tahun ini, sekolah menerima calon siswa kelas 1 melalui 4 jalur utama, yaitu Zonasi (minimal 70%), Afirmasi untuk siswa kurang mampu (15%), Perpindahan Tugas Orang Tua (5%), dan Jalur Prestasi (10%). Pengisian formulir online dapat diakses melalui modul SPMB di bawah ini untuk meminimalisir antrean fisik di sekolah.",
    date: "15 Mei 2026",
    category: "PPDB",
    image: "https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?auto=format&fit=crop&q=80&w=600",
    author: "Panitia PPDB",
  },
  {
    id: "news-5",
    title: "Kemah Bakti Regu Penggalang SDN 3 Menumbuhkan Jiwa Mandiri",
    excerpt: "Pendidikan karakter kepramukaan luar ruangan di lapangan desa Purwosari diisi dengan api unggun, tali-temali, dan baksos.",
    content: "Wonogiri — Mengasah ketangkasan fisik dan mental gotong royong, gerakan Pramuka gugus depan SDN 3 Purwosari menyelenggarakan Kemah Bakti Akhir Pekan. Kegiatan diisi dengan pelatihan tali temali sandi, penjelajahan menyusuri rute pedesaan, malam api unggun ekspresi bakat, serta bakti sosial pembagian sembako ringan untuk warga sekitar lokasi perkemahan.",
    date: "02 Mei 2026",
    category: "Ekstrakurikuler",
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&q=80&w=600",
    author: "Kak Pembina",
  },
  {
    id: "news-6",
    title: "Peringatan Hari Pendidikan Nasional 2026: Meneladani Ki Hadjar",
    excerpt: "Upacara Hari Pendidikan Nasional diikuti khidmat oleh siswa berpakaian adat Jawa lengkap dengan pameran literasi siswa.",
    content: "Wonogiri — Keluarga besar SDN 3 Purwosari memperingati Hari Pendidikan Nasional 2026 dengan khidmat. Seluruh guru dan murid mengenakan busana kejawen/adat tradisional Jawa. Setelah gelaran upacara bendera, dilanjutkan dengan pameran majalah dinding (mading) buatan murid serta unjuk bakat mendongeng cerita rakyat sebagai bentuk pelestarian warisan budaya lokal.",
    date: "02 Mei 2026",
    category: "Umum",
    image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600",
    author: "Tim Kurikulum",
  },
];

export const schoolAchievements: Achievement[] = [
  {
    id: "ach-1",
    title: "Juara I Lomba Cerdas Cermat (LCC) Umum",
    rank: "Juara 1",
    level: "Kecamatan Wonogiri",
    year: "2026",
    category: "Akademik",
    image: "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: "ach-2",
    title: "Juara II FLS2N Menyanyi Tunggal Putra",
    rank: "Juara 2",
    level: "Kabupaten Wonogiri",
    year: "2025",
    category: "Seni & Budaya",
    image: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: "ach-3",
    title: "Juara III Tari Kreasi Nusantara",
    rank: "Juara 3",
    level: "Eks Karesidenan Surakarta",
    year: "2026",
    category: "Seni & Budaya",
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: "ach-4",
    title: "Pramuka Garuda Berprestasi Utama",
    rank: "Predikat Utama",
    level: "Kabupaten Wonogiri",
    year: "2025",
    category: "Pramuka",
    image: "https://images.unsplash.com/photo-1533227268428-f9ed0900fb3b?auto=format&fit=crop&q=80&w=500",
  },
];

export const agendaEvents: AgendaEvent[] = [
  {
    id: "evt-1",
    title: "Pembagian Laporan Hasil Belajar (Rapor) Semester Genap",
    date: "20 Jun 2026",
    day: "20",
    month: "Jun",
    time: "08:00 - 11:30 WIB",
    location: "Ruang Kelas Masing-masing",
    category: "akademik",
  },
  {
    id: "evt-2",
    title: "Penerimaan & Verifikasi Berkas PPDB Tatap Muka",
    date: "22 Jun 2026",
    day: "22",
    month: "Jun",
    time: "07:30 - 12:30 WIB",
    location: "Aula Pertemuan Sekolah",
    category: "spmb",
  },
  {
    id: "evt-3",
    title: "Rapat Pleno Komite & Sosialisasi Program Sekolah TA 26/27",
    date: "04 Jul 2026",
    day: "04",
    month: "Jul",
    time: "09:00 - selesai",
    location: "Gedung Komite SDN 3",
    category: "umum",
  },
  {
    id: "evt-4",
    title: "Hari Pertama Masuk Sekolah & Masa Pengenalan Lingkungan Sekolah",
    date: "13 Jul 2026",
    day: "13",
    month: "Jul",
    time: "07:00 - 10:30 WIB",
    location: "Halaman & Kelas SDN 3",
    category: "akademik",
  },
];

export const galleryPhotos: GalleryPhoto[] = [
  {
    id: "gal-1",
    title: "Kebun Pembelajaran Hidroponik Adiwiyata",
    category: "fasilitas",
    image: "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&q=80&w=800",
    description: "Siswa diajak menanam sayur selada hidroponik sebagai bagian edukasi cinta alam lestari.",
  },
  {
    id: "gal-2",
    title: "Latihan Rutin Drumband Bhakti Senada",
    category: "kegiatan",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=800",
    description: "Kegiatan membahu formasi, melatih ritme, dan kekompakan tim dalam ekstrakurikuler musik.",
  },
  {
    id: "gal-3",
    title: "Geliat Semangat Siswa di Laboratorium Komputer Baru",
    category: "siswa",
    image: "https://images.unsplash.com/photo-1562774053-401386df9006?auto=format&fit=crop&q=80&w=800",
    description: "Fasilitas laptop penunjang materi literasi informatika, ujian ANBK, dan game logika sains.",
  },
  {
    id: "gal-4",
    title: "Rapat KKG Guru Memersiapkan Kurikulum Merdeka",
    category: "guru",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=800",
    description: "Diskusi bimbingan guru lintas jenjang guna memetakan metode ajar adaptif yang aman dan bahagia.",
  },
  {
    id: "gal-5",
    title: "Sudut Baca Ramah Anak & Perpustakaan",
    category: "fasilitas",
    image: "https://images.unsplash.com/photo-1568667256549-094345857637?auto=format&fit=crop&q=80&w=800",
    description: "Ruang teduh dambaan murid untuk tenggelam membaca komik edukasi, dongeng fabel, dan buku atlas bumi.",
  },
  {
    id: "gal-6",
    title: "Pemberian Makan Pangan Ibu Guru Sehat Alami",
    category: "kegiatan",
    image: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&q=80&w=800",
    description: "Hari konsumsi gizi seimbang: pembiasaan membawa bekal bervitamin tinggi tanpa pewarna instan.",
  },
  {
    id: "gal-7",
    title: "Upacara Pengibaran Duplikat Sang Merah Putih",
    category: "kegiatan",
    image: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&q=80&w=800",
    description: "Menanamkan khidmat berbangsa, kerapian jiwa korsp, dan penghormatan setinggi-tingginya bagi jasa pahlawan.",
  },
  {
    id: "gal-8",
    title: "Halaman Bermain Luar & Wahana Ketangkasan",
    category: "fasilitas",
    image: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&q=80&w=800",
    description: "Taman rindang beralaskan rumput aman untuk mengasah ketangkasan melompat, bersosialisasi, dan berlari gembira.",
  },
];

export const faqItems: FAQItem[] = [
  {
    id: "faq-1",
    question: "Berapakah batas usia minimal untuk mendaftar Kelas 1 SD?",
    answer: "Sesuai petunjuk teknis dinas pendidikan, batas usia minimal pendaftar adalah 6 tahun pada tanggal 1 Juli 2026. Prioritas seleksi utama (pagu penuh) diberikan untuk siswa yang telah genap berusia 7 tahun ke atas.",
  },
  {
    id: "faq-2",
    question: "Apakah dikenakan biaya gedung atau SPP bulanan?",
    answer: "Tidak ada. Sebagai lembaga sekolah dasar negeri di bawah naungan Kemendikbudristek dan Pemerintah Daerah Wonogiri, seluruh biaya operasional pendidikan telah disubsidi penuh oleh dana BOS. Siswa dibebaskan dari biaya SPP dan uang pendaftaran.",
  },
  {
    id: "faq-3",
    question: "Dokumen apa saja yang wajib dilampirkan saat daftar online/ulang?",
    answer: "Wali murid wajib mengunggah/menyerahkan: 1) Fotokopi Akta Kelahiran Calon Siswa, 2) Fotokopi Kartu Keluarga (KK) yang diterbitkan minimal 1 tahun lalu, 3) Fotokopi KTP Orang Tua / Wali serta 4) Pas foto berwarna calon siswa ukuran 3x4 (2 lembar).",
  },
  {
    id: "faq-4",
    question: "Bagaimana jika kakek/nenek anak yang tercantum di KK tetapi alamat berbeda?",
    answer: "Acuan utama domisili adalah Kartu Keluarga (KK) sah yang diterbitkan oleh Dinas Kependudukan dan Catatan Sipil setempat, tempat calon peserta didik berdomisili bersama orang tua/wali kandung sah.",
  },
  {
    id: "faq-5",
    question: "Apakah SDN 3 Purwosari memfasilitasi ekskul keagamaan?",
    answer: "Ya, kami memiliki program pembiasaan keagamaan pagi seperti Sholat Dhuha bersama, tadarus Iqra, bimbingan Khitobah, hafalan Juz Amma rutin (tahfidz), ekstrul Rebana Islami, serta pendampingan kerohanian non-muslim.",
  },
];

export const downloadFiles: DownloadFile[] = [
  {
    id: "dl-1",
    title: "Brosur PPDB Resmi SDN 3 Purwosari TA 2026/2027",
    size: "2.4 MB",
    type: "PDF Document",
    downloads: 142,
    url: "#",
  },
  {
    id: "dl-2",
    title: "Formulir Pendaftaran Siswa Baru (F-PPDB.01)",
    size: "1.1 MB",
    type: "PDF Document",
    downloads: 389,
    url: "#",
  },
  {
    id: "dl-3",
    title: "Alur Kartu Zonasi & Panduan Peta Radius Wonogiri",
    size: "820 KB",
    type: "PDF Document",
    downloads: 95,
    url: "#",
  },
  {
    id: "dl-4",
    title: "Tata Tertib Siswa, Jam Belajar, & Kode Etik Sekolah",
    size: "1.5 MB",
    type: "PDF Document",
    downloads: 210,
    url: "#",
  },
  {
    id: "dl-5",
    title: "Kalender Pendidikan & Pembagian Sesi Belajar TA 2026/2027",
    size: "1.9 MB",
    type: "PDF Document",
    downloads: 175,
    url: "#",
  },
];
